[2024-12-12T10:16:07.409+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T10:16:07.434+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summary_transaction.extract_task manual__2024-12-12T10:16:05.737344+00:00 [queued]>
[2024-12-12T10:16:07.446+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summary_transaction.extract_task manual__2024-12-12T10:16:05.737344+00:00 [queued]>
[2024-12-12T10:16:07.447+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-12-12T10:16:07.466+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): extract_task> on 2024-12-12 10:16:05.737344+00:00
[2024-12-12T10:16:07.505+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=651) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-12T10:16:07.519+0000] {standard_task_runner.py:72} INFO - Started process 653 to run task
[2024-12-12T10:16:07.508+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'summary_transaction', 'extract_task', 'manual__2024-12-12T10:16:05.737344+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/summary_transaction.py', '--cfg-path', '/tmp/tmpnx9ahx9c']
[2024-12-12T10:16:07.539+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask extract_task
[2024-12-12T10:16:07.749+0000] {task_command.py:467} INFO - Running <TaskInstance: summary_transaction.extract_task manual__2024-12-12T10:16:05.737344+00:00 [running]> on host fd39b762d5e6
[2024-12-12T10:16:07.897+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='summary_transaction' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T10:16:05.737344+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T10:16:05.737344+00:00'
[2024-12-12T10:16:07.903+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T10:16:08.062+0000] {base.py:84} INFO - Retrieving connection 'dbmaster'
[2024-12-12T10:16:08.086+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/summary_transaction.py", line 13, in extract_data
    cursor.execute(query)
psycopg2.errors.UndefinedTable: relation "transaction_data" does not exist
LINE 1: SELECT * FROM transaction_data
                      ^

[2024-12-12T10:16:08.114+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=summary_transaction, task_id=extract_task, run_id=manual__2024-12-12T10:16:05.737344+00:00, execution_date=20241212T101605, start_date=20241212T101607, end_date=20241212T101608
[2024-12-12T10:16:08.136+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T10:16:08.137+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task extract_task (relation "transaction_data" does not exist
LINE 1: SELECT * FROM transaction_data
                      ^
; 653)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/summary_transaction.py", line 13, in extract_data
    cursor.execute(query)
psycopg2.errors.UndefinedTable: relation "transaction_data" does not exist
LINE 1: SELECT * FROM transaction_data
                      ^

[2024-12-12T10:16:08.189+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-12-12T10:16:08.213+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T10:16:08.217+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
